<?php

namespace AppBundle\Repository;

/**
 * ConcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCurrentMonth($start, $end){
        $query = $this->getEntityManager()->createQuery('SELECT c FROM AppBundle:Concours c WHERE c.dateDebut BETWEEN :date_debut AND :date_fin');
        $query->setParameter('date_debut', $start);
        $query->setParameter('date_fin', $end);
        try {
            return $query->getArrayResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
