<?php

namespace AppBundle\Repository;

/**
 * OrganisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
