<?php

namespace AppBundle\Repository;

/**
 * PartitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartitionRepository extends \Doctrine\ORM\EntityRepository
{
}
