<?php

namespace AppBundle\Repository;

/**
 * Utilisateur_evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Utilisateur_evenementRepository extends \Doctrine\ORM\EntityRepository
{
}
