<?php

namespace AppBundle\Repository;

/**
 * UtilisateurEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
